services:
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: paradimesportal@gmail.com
      PGADMIN_DEFAULT_PASSWORD: paradimes@2025
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8085:80'
    restart: always
    networks:
      - sail
networks:
  sail:
    external: true
